// <auto-generated/>
#pragma warning disable CS0618
using BibleWell.Aquifer.API.Client.Resources.ParentResources;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BibleWell.Aquifer.API.Client.Resources
{
    /// <summary>
    /// Builds and executes requests for operations under \resources
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResourcesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The parentResources property</summary>
        public global::BibleWell.Aquifer.API.Client.Resources.ParentResources.ParentResourcesRequestBuilder ParentResources
        {
            get => new global::BibleWell.Aquifer.API.Client.Resources.ParentResources.ParentResourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BibleWell.Aquifer.API.Client.Resources.ResourcesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResourcesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resources", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BibleWell.Aquifer.API.Client.Resources.ResourcesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResourcesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resources", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
