// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BibleWell.Aquifer.API.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListParentResourcesResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>The displayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The licenseInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BibleWell.Aquifer.API.Client.Models.ResourceLicenseInfo? LicenseInfo { get; set; }
#nullable restore
#else
        public global::BibleWell.Aquifer.API.Client.Models.ResourceLicenseInfo LicenseInfo { get; set; }
#endif
        /// <summary>The localizations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::BibleWell.Aquifer.API.Client.Models.ParentResourcesLocalization>? Localizations { get; set; }
#nullable restore
#else
        public List<global::BibleWell.Aquifer.API.Client.Models.ParentResourcesLocalization> Localizations { get; set; }
#endif
        /// <summary>The resourceType property</summary>
        public global::BibleWell.Aquifer.API.Client.Models.ResourceType? ResourceType { get; set; }
        /// <summary>The shortName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShortName { get; set; }
#nullable restore
#else
        public string ShortName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BibleWell.Aquifer.API.Client.Models.ListParentResourcesResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BibleWell.Aquifer.API.Client.Models.ListParentResourcesResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::BibleWell.Aquifer.API.Client.Models.ListParentResourcesResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetStringValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "licenseInfo", n => { LicenseInfo = n.GetObjectValue<global::BibleWell.Aquifer.API.Client.Models.ResourceLicenseInfo>(global::BibleWell.Aquifer.API.Client.Models.ResourceLicenseInfo.CreateFromDiscriminatorValue); } },
                { "localizations", n => { Localizations = n.GetCollectionOfObjectValues<global::BibleWell.Aquifer.API.Client.Models.ParentResourcesLocalization>(global::BibleWell.Aquifer.API.Client.Models.ParentResourcesLocalization.CreateFromDiscriminatorValue)?.AsList(); } },
                { "resourceType", n => { ResourceType = n.GetEnumValue<global::BibleWell.Aquifer.API.Client.Models.ResourceType>(); } },
                { "shortName", n => { ShortName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("code", Code);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteIntValue("id", Id);
            writer.WriteObjectValue<global::BibleWell.Aquifer.API.Client.Models.ResourceLicenseInfo>("licenseInfo", LicenseInfo);
            writer.WriteCollectionOfObjectValues<global::BibleWell.Aquifer.API.Client.Models.ParentResourcesLocalization>("localizations", Localizations);
            writer.WriteEnumValue<global::BibleWell.Aquifer.API.Client.Models.ResourceType>("resourceType", ResourceType);
            writer.WriteStringValue("shortName", ShortName);
        }
    }
}
#pragma warning restore CS0618
