// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace BibleWell.Aquifer.API.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ResourceType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "Guide")]
        #pragma warning disable CS1591
        Guide,
        #pragma warning restore CS1591
        [EnumMember(Value = "Dictionary")]
        #pragma warning disable CS1591
        Dictionary,
        #pragma warning restore CS1591
        [EnumMember(Value = "StudyNotes")]
        #pragma warning disable CS1591
        StudyNotes,
        #pragma warning restore CS1591
        [EnumMember(Value = "Images")]
        #pragma warning disable CS1591
        Images,
        #pragma warning restore CS1591
        [EnumMember(Value = "Videos")]
        #pragma warning disable CS1591
        Videos,
        #pragma warning restore CS1591
    }
}
