//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleWell.App.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BibleWell.App.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string BiblePage_Title {
            get {
                return ResourceManager.GetString("BiblePage_Title", resourceCulture);
            }
        }
        
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        public static string DevPage_Title {
            get {
                return ResourceManager.GetString("DevPage_Title", resourceCulture);
            }
        }
        
        public static string GuidePage_Title {
            get {
                return ResourceManager.GetString("GuidePage_Title", resourceCulture);
            }
        }
        
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        public static string LibraryPage_Title {
            get {
                return ResourceManager.GetString("LibraryPage_Title", resourceCulture);
            }
        }
        
        public static string MainView_Menu_Bible {
            get {
                return ResourceManager.GetString("MainView_Menu_Bible", resourceCulture);
            }
        }
        
        public static string MainView_Menu_Guide {
            get {
                return ResourceManager.GetString("MainView_Menu_Guide", resourceCulture);
            }
        }
        
        public static string MainView_Menu_Resources {
            get {
                return ResourceManager.GetString("MainView_Menu_Resources", resourceCulture);
            }
        }
        
        public static string ResourcesPage_Title {
            get {
                return ResourceManager.GetString("ResourcesPage_Title", resourceCulture);
            }
        }
        
        public static string Test_Chilly {
            get {
                return ResourceManager.GetString("Test_Chilly", resourceCulture);
            }
        }
        
        public static string HomePage_Profile {
            get {
                return ResourceManager.GetString("HomePage_Profile", resourceCulture);
            }
        }
        
        public static string HomePage_ResourceManager {
            get {
                return ResourceManager.GetString("HomePage_ResourceManager", resourceCulture);
            }
        }
        
        public static string HomePage_Feedback {
            get {
                return ResourceManager.GetString("HomePage_Feedback", resourceCulture);
            }
        }
        
        public static string HomePage_About {
            get {
                return ResourceManager.GetString("HomePage_About", resourceCulture);
            }
        }
        
        public static string HomePage_ChangeExperience {
            get {
                return ResourceManager.GetString("HomePage_ChangeExperience", resourceCulture);
            }
        }
        
        public static string HomePage_CurrentExperience {
            get {
                return ResourceManager.GetString("HomePage_CurrentExperience", resourceCulture);
            }
        }
    }
}
