//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleWell.App.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainView {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainView() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BibleWell.App.Resources.MainView", typeof(MainView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Chilly {
            get {
                return ResourceManager.GetString("Chilly", resourceCulture);
            }
        }
        
        public static string Bible {
            get {
                return ResourceManager.GetString("Bible", resourceCulture);
            }
        }
        
        public static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        public static string Home_Page {
            get {
                return ResourceManager.GetString("Home Page", resourceCulture);
            }
        }
        
        public static string Guide_Page {
            get {
                return ResourceManager.GetString("Guide Page", resourceCulture);
            }
        }
        
        public static string Library_Page {
            get {
                return ResourceManager.GetString("Library Page", resourceCulture);
            }
        }
        
        public static string Resources_Page {
            get {
                return ResourceManager.GetString("Resources Page", resourceCulture);
            }
        }
        
        public static string Dev_Page {
            get {
                return ResourceManager.GetString("Dev Page", resourceCulture);
            }
        }
    }
}
