// <auto-generated/>
#pragma warning disable CS0618
using BibleWell.Aquifer.API.Client.PushNotifications.DeviceInstallation;
using BibleWell.Aquifer.API.Client.PushNotifications.Requests;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BibleWell.Aquifer.API.Client.PushNotifications
{
    /// <summary>
    /// Builds and executes requests for operations under \push-notifications
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PushNotificationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The deviceInstallation property</summary>
        public global::BibleWell.Aquifer.API.Client.PushNotifications.DeviceInstallation.DeviceInstallationRequestBuilder DeviceInstallation
        {
            get => new global::BibleWell.Aquifer.API.Client.PushNotifications.DeviceInstallation.DeviceInstallationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The requests property</summary>
        public global::BibleWell.Aquifer.API.Client.PushNotifications.Requests.RequestsRequestBuilder Requests
        {
            get => new global::BibleWell.Aquifer.API.Client.PushNotifications.Requests.RequestsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BibleWell.Aquifer.API.Client.PushNotifications.PushNotificationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PushNotificationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/push-notifications", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BibleWell.Aquifer.API.Client.PushNotifications.PushNotificationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PushNotificationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/push-notifications", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
