// <auto-generated/>
#pragma warning disable CS0618
using BibleWell.Aquifer.API.Client.Languages;
using BibleWell.Aquifer.API.Client.PushNotifications;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BibleWell.Aquifer.API.Client
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AquiferWellApiClient : BaseRequestBuilder
    {
        /// <summary>The languages property</summary>
        public global::BibleWell.Aquifer.API.Client.Languages.LanguagesRequestBuilder Languages
        {
            get => new global::BibleWell.Aquifer.API.Client.Languages.LanguagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pushNotifications property</summary>
        public global::BibleWell.Aquifer.API.Client.PushNotifications.PushNotificationsRequestBuilder PushNotifications
        {
            get => new global::BibleWell.Aquifer.API.Client.PushNotifications.PushNotificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BibleWell.Aquifer.API.Client.AquiferWellApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AquiferWellApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
